README.md
Updating docs for public visibility.
N/A
=> docs: touch up readme for public visibility

README.md
=> docs: remove duplicate badges

internal/metrics/metrics.go, internal/route/router.go, internal/server/web_server.go
Instruments basic metrics for monitoring inbound requests/responses and forwards to upstream nodes. Useful for tracking
Ran with a config with 1 upstream pointed at https://rpc.ankr.com/eth. Ran a few curl commands and checked metrics:
```bash
curl --location --request POST 'localhost:8080' \
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc":"2.0",
"method":"eth_blockNumber",
"params":[],
"id":1
}'
curl --location --request POST 'localhost:8080' \
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc":"2.0",
"method":"dummy_method",
"params":[],
"id":1
}'
```
=> feat: instrument more rpc and upstream metrics

README.md
=> chore: Expose metrics port in sample docker run cmd

internal/server/web_server.go
Health check handler
Local
```
➜  node-gateway git:(main) ✗ curl localhost:8080/health 
OK%                   
```
=> feat: healthcheck endpoint

README.md
=> fix: put badges on same line

internal/server/web_server.go
=> fix: default client to unknown if not passed

internal/jsonrpc/jsonrpc.go, internal/server/web_server.go
Visibility into errors when decoding request
Currently running, helped us debug issue where gateway isn't deserializing batch requests properly
=> feat: better logging deserialization

internal/route/router.go
Also publish image by commit name too.
=> fix: debug log for upstream id failed request was routed to

internal/route/node_filter.go
causing nil pointer exceptions
```
Oct 26 14:37:25.273
github.com/satsuma-data/node-gateway/internal/route.(*SimpleRouter).Route(0xc00020ca10, {0xadd2b8?, 0xc0014777a0}, {0xadc770, 0xc00168f380})
Oct 26 14:37:25.273
/app/internal/route/filtering_strategy.go:20 +0x27
Oct 26 14:37:25.273
github.com/satsuma-data/node-gateway/internal/route.(*FilteringRoutingStrategy).RouteNextRequest(0xc0002380c0, 0xadc770?, {0x80?, 0xf3?})
Oct 26 14:37:25.273
/app/internal/route/filtering_strategy.go:36 +0x39f
Oct 26 14:37:25.273
github.com/satsuma-data/node-gateway/internal/route.(*FilteringRoutingStrategy).filter(0xc0002380c0, 0x98?, {0x80?, 0x94?})
Oct 26 14:37:25.273
/app/internal/route/node_filter.go:28 +0xa3
Oct 26 14:37:25.273
github.com/satsuma-data/node-gateway/internal/route.(*AndFilter).Apply(0xc0 …
```
=> fix: initialize logger in a couple of filters

internal/checks/blockheight.go
Actually we are emitting metrics for this. Added a debug log too.
=> fix: emit debug log on blockheight metric from websockets

internal/route/request_executor.go
=> fix: add upstream ids to error logs

internal/route/request_executor.go
While testing the cache in the staging environment, I found some weird edge cases where `resp` and `respBody` could be `nil` even though no errors were raised.  `respBody` can be nil without error on an empty JSON RPC response, but I'm not sure how `httpClient.Do` can return an empty response without error.  
Testing locally.  Also tested via SSH tunneling to exercise the Elasticache instance.
=> fix: error handling and better error logging

internal/cache/rpc_cache.go, internal/route/request_executor.go
The golang-redis/cache library supports request coalescing, which means that multiple identical requests to the cache will only result in a single request to origin.
However, this means that errors can also be returned in the scenario. After looking at logs, this is very common for node-gateway because the graph-nodes are constantly getting null results from eth_getTransactionReceipt calls for new transactions.
Certain errors that come from request coalescing can be handled(null result and JSON RPC Errors). We have to fake a response and modify the response body to match the original request.
Running locally + deployed to staging.
=> fix: error handling with request coalescing

internal/checks/blockheight.go, internal/checks/blockheight_test.go, internal/checks/manager_test.go, internal/checks/peers.go, internal/checks/peers_test.go, internal/checks/syncing.go, internal/checks/syncing_test.go, internal/client/ethereum_client.go
We need to attach additional request headers to health checks so auth related headers can be sent. Otherwise, health check requests may fail.
=> fix: add additional request headers to health checks

internal/route/request_executor.go, internal/route/request_executor_test.go
=> fix: return httpResp even in err scenarios

internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go, internal/metrics/metrics.go, internal/route/request_executor_test.go, internal/server/object_graph.go
Adding additional metrics to capture performance of the cache and pinpoint where the bottlenecks are if we experience issues with Redis in the future.
=> feat: adding additional metrics to cache

internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go, internal/config/config.go, internal/config/config_test.go, internal/metrics/metrics.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/server/object_graph.go
=> feat: support reader and writer redis endpoint

internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go, internal/config/config.go, internal/config/config_test.go, internal/metrics/metrics.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/server/object_graph.go
=> fix: dont use cluster client

.github/workflows/golangci-lint.yml, .golangci.yml, README.md, internal/checks/blockheight_test.go, internal/checks/manager_test.go, internal/route/node_filter.go, internal/route/router_test.go, internal/server/web_server_e2e_test.go, internal/util/context.go
=> chore: remove exportloopref and gomnd linters

.github/workflows/test.yml, internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go
=> feat: cache eth_getBlockByHash

internal/cache/rpc_cache.go
=> feat: cache eth_getBlockReceipts

internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go, internal/config/config.go, internal/config/config_test.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/route/router.go, internal/server/object_graph.go
=> feat: configurable cache TTL part 1 (no-op)
