satsuma-xyz/node-gateway

scripts/release.sh
There is a permissions issue pushing images using the production account, but the dianwen account has been added as a collaborator, so just authenticate with that account.
=> ci: docker release login with dianwen

README.md
Explain how you may want to use the gateway.
=> docs: example use cases in README

scripts/release.sh
As discussed in launch last Friday
Also 
Commented parts of the script out to test IsProductionRelease
```
➜  node-gateway git:(publish_github_tag) ✗ ./scripts/release.sh b9147f3309d8cdcd09533265016c3aaa8dc78735 0.1.0 dianwen/satsuma-gateway-test
➜  node-gateway git:(publish_github_tag) ✗ ./scripts/release.sh b9147f3309d8cdcd09533265016c3aaa8dc78735 0.1.0 satsumaxyz/node-gateway
Have you already tested this image by pushing it up to the satsumaxyz/node-gateway Docker registry? [y/N] y
```
=> build: Publish GitHub tag in release script

scripts/lint_commit_message.sh
```
➜  node-gateway git:(more_metrics) ✗ ./scripts/lint_commit_message.sh "fix: H"
Commit message does follow the conventional commit format.
➜  node-gateway git:(more_metrics) ✗ ./scripts/lint_commit_message.sh "fix: h"
➜  node-gateway git:(more_metrics) ✗ ./scripts/lint_commit_message.sh "fix: hi"
```
=> ci: make sure commit msg starts with lower case after the commit type

internal/checks/blockheight.go, internal/checks/check.go, internal/checks/peers.go, internal/checks/syncing.go, internal/metrics/metrics.go
Metrics for health checks — counts, errors, latencies, check results
```
node_gateway_healthcheck_block_height{endpoint_id="satsuma-erigon-1",url="http://54.146.12.232:8545"} 1.5454965e+07
node_gateway_healthcheck_block_height{endpoint_id="satsuma-erigon-2",url="http://35.171.183.44:8545"} 1.5454965e+07
node_gateway_healthcheck_block_height_duration_seconds_bucket{endpoint_id="satsuma-erigon-1",url="http://54.146.12.232:8545",le="0.1"} 5
node_gateway_healthcheck_block_height_duration_seconds_sum{endpoint_id="satsuma-erigon-1",url="http://54.146.12.232:8545"} 0.45845249899999996
node_gateway_healthcheck_block_height_duration_seconds_count{endpoint_id="satsuma-erigon-1",url="http://54.146.12.232:8545"} 5
...
...
node_gateway_healthcheck_block_height_total{endpoint_id="satsuma-erigon-1",url=" …
```
=> feat: metrics on health checks

internal/metrics/metrics.go
* Removing the URL label as I think it's unnecessary. `upstream_id` is descriptive enough
* Remove the `total` metrics - we can use `duration.count` instead
* Rename the label `endpoint_id` to `upstream_id` for consistency
* 
Ran it and seeing metrics in data dog
=> perf: remove extra metrics

internal/checks/manager.go
1s too frequent for node providers. The interval should be configurable per upstream.
=> fix: change health check interval to 5s

cmd/gateway/main.go, internal/route/router.go
* Logging client in certain logs is very helpful 
* Make the log formats between production/development mode the same. Single format allows for consistent ingestion on the Datadog side. Also format log timestamps as human readable timestamps  instead of epoch millis. 
`-e ENV=production -e LOG_LEVEL=debug` works
=> feat: better logging settings, log client in certain logs

configs/config.sample.yml, internal/config/config.go, internal/config/config_test.go, internal/metadata/request_metadata.go, internal/metadata/request_metadata_parser.go, internal/metadata/request_metadata_parser_test.go, internal/mocks/RoutingStrategy.go, internal/route/filtering_strategy.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/route/router.go, internal/route/routing_strategy.go, internal/route/routing_strategy_test.go, internal/server/web_server.go
- Added a new NodeFilter to route state RPC methods only to archive nodes.
- Added `nodeType` to the `UpstreamConfig` so that we know which nodes maintain full historic state.
Unit tests for the `RequestMetadataParser` and `SimpleIsStatePresentFilter`.
=> feat: route state-backed requests to archive nodes

internal/checks/manager.go, internal/mocks/HealthCheckManager.go, internal/mocks/Router.go, internal/mocks/RoutingStrategy.go, internal/route/router.go, internal/route/router_test.go, internal/server/web_server.go, internal/server/web_server_e2e_test.go
This PR adds basic support for running end-to-end tests that cover the whole routing. It uses in-process servers from the `net/http/httptest` package to bring up fake upstreams, and returns legitimately-looking responses to health check requests. Each test can then configure additional handlers for other RPC methods and check that they are routed as expected.
Notable changes:
1. **I added `IsInitialized` methods to `Router` and `HealthCheckManager`.** I needed a way to confirm that the gateway is fully up and running - in particular, that at least one iteration of the health checks has already executed. Without this, we can't be sure if the behaviour we're testing actually respects the health checks.
2. **I changed the `/health` endpoint to reflect the above.** I thought I was going to …
=> test: add end-to-end tests using fake upstreams

configs/config.sample.yml, internal/config/config.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/server/web_server.go
We want to be able to tolerate some lag in certain situations. For example, we might want to favour our own node over a node provider even if we're slightly behind head. This PR keeps routing to nodes as long as they are within 10 blocks of the max height.
Added unit tests for new filter.
=> feat: route to nodes even if slightly behind max height

internal/metadata/request_metadata.go, internal/metadata/request_metadata_parser.go, internal/metadata/request_metadata_parser_test.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/server/web_server.go
=> Trace filter

scripts/internal-release.sh, scripts/public-release.sh
* Ported over subgraph gateway's release.sh for an `internal-release`.sh - to deploy to ECR.
* For now, release is done locally and manually: `./scripts/iinternal-release.sh $GIT_COMMIT_SHA`.
Why not DockerHub? I think there are benefits to keeping it consistent with our other internal Docker images. Let's only use DockerHub for open source releases.
Deployed a version to ECR already
=> feat: internal-release.sh to deploy to ECR

internal/jsonrpc/jsonrpc.go, internal/jsonrpc/jsonrpc_test.go, internal/metadata/request_metadata_parser.go, internal/metadata/request_metadata_parser_test.go, internal/metrics/metrics.go, internal/mocks/HealthCheckManager.go, internal/mocks/Router.go, internal/mocks/RoutingStrategy.go, internal/route/request_executor.go, internal/route/router.go, internal/route/router_test.go, internal/server/web_server.go, internal/server/web_server_e2e_test.go, internal/server/web_server_test.go
* Why support batching?
*  Moving to relying on free node providers. Many of these impose stringent rate limiting, which we can hopefully get around by batching requests.
* Performance. Some preliminary tests suggest that batching will speed up initial indexing. Further investigation is needed here.
* We discussed the idea of splitting of batches. 
* For example if one part of the batch is stateful requests and another part is non-stateful, should we split the batch up, send them to their respective upstreams, and then merge the results? 
* Should we split up large batches and route them to upstreams in parallel in order to decrease latency?
* We landed on not splitting up batches due to tricky handling of partial failures and also the possibility of data inconsistencies of getting routed …
=> feat: support batch requests

internal/checks/blockheight.go, internal/checks/blockheight_test.go, internal/checks/manager.go, internal/checks/manager_test.go, internal/checks/peers.go, internal/checks/peers_test.go, internal/checks/syncing.go, internal/checks/syncing_test.go, internal/client/ethereum_client.go, internal/metrics/metrics.go, internal/mocks/EthClient.go, internal/route/router.go, internal/route/router_test.go, internal/server/web_server.go, internal/server/web_server_e2e_test.go
This PR introduces a `MetricContainer` that can be used to pre-fill a set of metric labels. It'll be used in a follow-up PR to create a separate container per chain to enable multi-chain support.
1. Started a metric server in one of the e2e tests
2. Added a `time.Sleep` at the end
3. Queried the metrics endpoint and verified that metrics are still emitted correctly.
=> refactor: add metrics.Container to prepare for per-chain metrics

cmd/gateway/main.go, internal/checks/blockheight.go, internal/checks/blockheight_test.go, internal/checks/manager.go, internal/checks/manager_test.go, internal/checks/peers.go, internal/checks/peers_test.go, internal/checks/syncing.go, internal/checks/syncing_test.go, internal/route/filtering_strategy.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/route/request_executor.go, internal/route/router.go, internal/route/router_test.go, internal/route/routing_strategy.go, internal/route/routing_strategy_test.go, internal/server/web_server.go, internal/server/web_server_e2e_test.go, internal/server/web_server_test.go
This PR introduces a `logger` field into all objects that are operating on a single chain level. This enables creating a separate logger for each chain when we add multi-chain support.
(Testing from a follow-up PR) Confirmed that logs contain a `chainName` field.
=> refactor: pass logger into object graph

internal/checks/blockheight_test.go, internal/checks/manager_test.go, internal/checks/peers_test.go, internal/checks/syncing_test.go, internal/config/config.go, internal/config/config_test.go, internal/metrics/metrics.go, internal/route/router_test.go, internal/server/web_server.go
Add required `ChainName` config and set it as a label in logs and metrics.
=> feat: add chain name config

cmd/gateway/main.go, configs/config.sample.yml, go.mod, go.sum, internal/checks/blockheight_test.go, internal/checks/manager_test.go, internal/checks/peers_test.go, internal/checks/syncing_test.go, internal/config/config.go, internal/config/config_test.go, internal/config/config_test_data.go, internal/mocks/EthClient.go, internal/mocks/Router.go, internal/route/router.go, internal/route/router_collection.go, internal/route/router_test.go, internal/server/health_check_handler.go, internal/server/object_graph.go, internal/server/rpc_handler.go, internal/server/web_server.go, internal/server/web_server_e2e_test.go, internal/server/web_server_test.go
High-level overview of changes in this PR:
1. **Change config format to support multiple chains.** All config settings except for the Port are moved at the chain level.
2. **Create a separate object graph for each chain.** 
3. **Register per-chain handlers into the `ServeMux` at `/<chain_name>`.**
4. **Add an `X-Upstream-ID` header.** This is useful so that clients know which upstream a given request went to. In particular, I'm using it to verify the end-to-end test is behaving as expected.
5. **Enable logging in tests.** I was hitting some panics that we have logging for, but zap uses a no-op logger by default. I changed it to a WARN logger.
Added end-to-end test with two chains configured and verified that requests go to the correct object graph - both by checking the new …
=> feat: support multiple chains in a single process

internal/server/object_graph.go
Hook up high level metrics. They were missing.
```
➜  node-gateway git:(main) ✗ 
➜  node-gateway git:(main) ✗ curl localhost:9090 | grep rpc_requests
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 58508    0 58508    0     0  6510k      0 --:--:-- --:--:-- --:--:-- 55.7M
➜  node-gateway git:(main) ✗ curl localhost:8080/eth
404 page not found
➜  node-gateway git:(main) ✗ curl localhost:8080/mainnet
{"message":"Method not allowed."}%                                                                                                                                                    
➜  node-gateway git:(main) ✗ curl localhost:9090 | grep rpc_requests
% Total    % Received % Xferd  Average Speed   Time    Time …
```
=> fix: hook up high level metrics

internal/metadata/request_metadata.go, internal/metadata/request_metadata_parser.go, internal/metadata/request_metadata_parser_test.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/server/object_graph.go
From `indexing using single node vs gateway test`, we found that routing `eth_getLogs` to full nodes is much slower than routing them to archive nodes, which significantly slows down initial indexing.
The reason why `eth_getLogs` is slower seems be partially rooted in how the clients are implemented (e.g. Geth/Bor vs Erigon). Therefore a blanket filter like in this PR may not hold for all clients. Currently we only run Geth/Bor/Erigon so this should be OK.
https://www.notion.so/satsuma-xyz/Indexing-on-gateway-vs-single-node-25825148e5a648bda892339900889b22
Tested locally and verified `eth_getLogs` requests are getting routed to archive
=> feat: route eth_getLogs to archive node

internal/checks/blockheight.go, internal/checks/check.go, internal/checks/peers.go, internal/checks/syncing.go
Lack of timeouts was causing monitoring to get [stuck](https://github.com/satsuma-data/node-gateway/blob/e6e71622712e4563e91a66ff42986b2b00a3891b/internal/checks/manager.go#L161-L190) and prolonged the [outage](https://www.notion.so/satsuma-xyz/Polygon-stack-outage-104195e1f96e4c7da1de4746f739b637) yesterday.
=> fix: timeout for healthchecks

go.mod, go.sum, internal/jsonrpc/jsonrpc.go, internal/jsonrpc/jsonrpc_test.go, internal/route/router.go, internal/route/router_test.go, internal/server/web_server_e2e_test.go
JSON RPC requests can omit the ID field to signal that the request is a notification: https://www.jsonrpc.org/specification#notification. These notification requests are not expected to have a response.
The SingleRequestBody model in the jsonrpc module uses the `omitempty` tag on the ID field.  The default "zero" value for an int64 in Golang is zero.  This means that any JSONRPC requests with ID of zero will not have the ID field present.  This causes the request to look like a notification, and the resulting response will have content-length of zero as well.
The graph-node uses a library called rust-web3 to make the JSONRPC requests to node providers.  This library ends up making requests that have ID set to 0 in the request.  When pointed to the node-gateway, the request hits the bug …
=> fix: turn JSON RPC request body ID to pointer

internal/client/ethereum_client.go, internal/route/request_executor.go
Some node providers like Chainstack check auth headers and will 401 the request if the header is empty, even if we're using an unauthed endpoint. The fix is to not send auth headers for health checks and routing of requests if basic auth credentials aren't defined in the config.
Tested locally by hooking it up to a node provider that checks auth headers.
=> fix: only include auth headers if basic auth is defined

internal/config/config.go, internal/config/config_test.go, internal/metadata/request_metadata.go, internal/metadata/request_metadata_parser.go, internal/metadata/request_metadata_parser_test.go, internal/route/node_filter.go, internal/route/node_filter_test.go, internal/route/router.go, internal/route/router_test.go, internal/server/object_graph.go
RFC: https://www.notion.so/satsuma-xyz/Mini-RFC-Node-Gateway-Method-based-routing-eedf6c5c29b048239dbfd7622ad297e2?d=8d04ff9cdd804a64b1c182d0ae650102#9a7a96d9c8d34f2ebbcb96569e7caa75
* Decided to strip out `isStateRequiredForMethod` and `IsTraceMethod` from `RequestMetadata ` and replace is with just plain method names (`Methods []string`). Then in the `node_filter` we check each method and compare with the `enabled|disabled` list as well as if the methods are archive or not.
* Test in staging before going to prod.
* The `eth_getLogs` -> archive logic is still here. I plan to remove it once we deploy this + update the node-gateway config to use the `method` config block to control this. Then, I'll send out a PR to remove the logic.
Config 1:
```
- id: geth-eth-full-prod-1
httpURL: …
```
=> feat: method-based routing

internal/route/node_filter.go
We already have the new node-gateway-config in place already to disable `eth_getLogs` on specific full nodes (bor + geth). This hack is safe to remove.
=> fix: remove eth_getLogs hardcode

configs/config.sample.yml, internal/checks/peers.go, internal/checks/peers_test.go, internal/config/config.go
Optimism returns peer count of 0, so we need to skip the check to use Optimism nodes in the gateway.
Tested locally that we can route requests to optimism nodes with `skipPeerCountCheck: true`.
=> feat: option to skip peer count checks on an upstream

internal/route/node_filter.go
According to https://github.com/ethereum/go-ethereum/issues/25534, the `eth_syncing` check doesn't seem to reflect useful information for the node gateway:
> The eth_syncing is set to true by the downloader, when it downloads the N blocks it needs from peers. If you have fallen behind, that can be a pretty quick thing.
> Just because "a higher block exists somewhere", that doesn't mean eth_syncing becomes set to true. We look only at the local behaviour: are we in a sync-cycle?
We've had this check cause flakes lately where a node is within the block lag limit, but it returns "syncing" so we stop routing requests to it. Relying on block lag only appears to be more accurate.
Not deleting the relevant logic for now in case we decide we do want to re-enable it at some point in the near …
=> chore: disable eth_syncing check

README.md, configs/config.sample.yml
Really small docs changes.
Going to make new release using v0.1.1 using `scripts/public-release.sh`.
=> docs: update

internal/jsonrpc/jsonrpc.go, internal/jsonrpc/jsonrpc_test.go, internal/route/router_test.go, internal/server/web_server_e2e_test.go, internal/server/web_server_test.go
We have seen several cases where the node-gateway responds to a graph-node with a missing `result` field. This results in an error message: `"failed to deserialize response: data did not match any variant of untagged enum Output"` that is difficult to debug. It also shows up in logs on customer subgraph dashboards, which leads to confusion for the end-user.
The main issue is that nodes will respond with `result` as null, which will get removed during unmarshaling due to the `omitempty` tag. In our case, we want to differentiate between an implicit null and an explicit null. We don't want the `result` field when it is not set(implicit), but we DO want `"result": null`(explicit). This setup is not easy to do out of the box with JSON tags. We also can't use the pointer trick because nil is …
=> fix: support null result in JSONRPC response

internal/route/filtering_strategy.go, internal/route/node_filter.go, internal/route/node_filter_test.go
If an upstream travels back in block height a bit, we won't route to it because we set the max height in each group across all checks instead of within 1 check. This is why requests arent getting routed to BSC blast even though it's the only node in a group and it's not lagging much.
It's not a complete fix since it doesn't handle multiple nodes in a PG, but doesn't introduce much tech debt and can work in conjunction with the actual fix to set block height in each group based on the most recent round of checks.
=> fix: pass the max height in each group check if there is only one node

configs/config.sample.yml, internal/cache/rpc_cache.go, internal/config/config.go, internal/config/config_test.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/route/router.go, internal/route/router_test.go, internal/server/object_graph.go
Transactions must expire quickly in the cache due to potential reorgs in the chain.  We will set the TTL for each chain in the configuration.
A TTL of 0 will disable the cache. This means not setting the TTL explicity will disable the cache.
The redis-cache library will set the ttl to 1 hour when it finds `0 < ttl < 1s`, so we error out in this case when validating the config.
Running locally + unit tests.
=> feat: Cache config ttl

configs/config.sample.yml, internal/cache/rpc_cache.go, internal/config/config.go, internal/config/config_test.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/route/router.go, internal/route/router_test.go, internal/server/object_graph.go
RPC nodes will respond with `null` result in the JSON RPC response often times for new transaction hashes.  We should treat these similarly to JSON RPC responses that have `Error` field set, where the result is not cached and the response is sent back to the user without changes.  In these cases, the `graph-node` will automatically retry the request when it receives the response with the `null` result.
Technically, we could do some retries internally within `node-gateway` as well, but I think that logic is more complicated and the performance improvement is still unknown.  It would mainly save roundtrips between the indexers and node-gateway itself, which is less important than saving round trips from the node-gateway and RPC nodes.
Tested locally and on staging environment.
=> fix: handle null result in RPC response

internal/cache/rpc_cache.go, internal/metrics/metrics.go, internal/route/request_executor.go, internal/route/request_executor_test.go, internal/route/router.go
Cleaned up some of the JSONRPC request metrics that are not used by dashboards right now. They have most of the same information as the corresponding upstream request metric. The only one that I could not remove as easily was the JSONRPC request error metric, which is more specific to the Error field in the JSON RPC response. This has a real use compared to the general upstream request error metric that measures non-200s.
The cached variable that is passed up to the metric does not exactly mean that it was a real cache hit to redis. The go-redis/cache library does not expose its internal cached state, so we can only try our best. If the Do() function is entered at all, we assume that the result was not cached. Otherwise, we assume that the result was cached. Technically, this means that …
=> feat: add cached tag for request metrics

internal/checks/check.go, internal/checks/peers_test.go
When restarting polygon nodes, I noticed that it sometimes takes > 10 minutes to get to 5 peers. The node will sync with fewer peers. The upside of having the node available for usage earlier outweighs the downside of more peers (more trusted data).
=> chore: reduce peer check count to 3 peers

configs/config.sample.yml, internal/config/config.go, internal/config/config_test.go, internal/route/request_executor.go
This is needed to support Sky Mavis's Ronin JSON RPC endpoint, which requires a custom auth header. https://docs.skymavis.com/reference/ronin-json-rpc#using-with-web3js-and-ethersjs-library
Testing locally to ensure we can route to requests when the `requestHeaders` config is present for ronin and absent for upstreams that don't require it.
=> feat: include additional request headers

cmd/gateway/main.go, internal/metrics/metrics.go
As title
- Ran server locally 
- Verified metric is recorded and exposed properly in Prometheus. 
- Sanity check requests still work
Metrics:
```
➜  node-gateway git:(brianluong/track_file_descirptors) ✗ curl --silent localhost:9090/metrics | grep file_descriptors_used | grep -v '#'
node_gateway_file_descriptors_used 10
```
Request:
```
➜  node-gateway git:(main) ✗ curl --silent -k --request POST --url 'localhost:8080/blast-mainnet' --header 'accept: application/json' --header 'content-type: application/json' --data '
{
"id": 1,
"jsonrpc": "2.0",
"method": "eth_getBlockByNumber",
"params": [
"latest",
false
]
}'
{"jsonrpc":"2.0","result":{"baseFeePerGas":"0x97022","blobGasUsed":"0x0","difficulty":"0x0","excessBlobGas":"0x0","extraData":"0x","gasLimit...................
```
=> feat: record file descriptors used as a prom metric

internal/cache/rpc_cache.go, internal/cache/rpc_cache_test.go, internal/metrics/metrics.go, internal/route/request_executor_test.go, internal/server/object_graph.go
- go back to using cache lib, but just use basic get/set commands (not the `Once` pipelining command). Main reason is there's a local cache implementation that I overlooked earlier, which can help us. The cache lib also implements a binary SerDe library which could make things faster.
- Use local cache
- Use `SetNX` (only set if key doesn’t exist) instead of `Set`
- metrics on Redis conns established - this is useful for debugging
Running in staging rn
=> feat: several improvements to Redis

Dockerfile
Adding instadefi's SSL cert to the store so we can make rpc requests against their rpc.
Tested running the commands on a docker image locally and then doing a curl to the new https endpoint.
```
➜  node-gateway git:(main) ✗ docker run -it --entrypoint /bin/sh 694773929020.dkr.ecr.us-east-1.amazonaws.com/node-gateway:0206d4e6a3f3a73ea9855585be14b02b72072374
Unable to find image '694773929020.dkr.ecr.us-east-1.amazonaws.com/node-gateway:0206d4e6a3f3a73ea9855585be14b02b72072374' locally
0206d4e6a3f3a73ea9855585be14b02b72072374: Pulling from node-gateway
550f8bf8502c: Pull complete
f526dc720ed7: Pull complete
6d685b842c63: Pull complete
Digest: sha256:c5ba4bc0a3292a1e9ff8be23aa13718270d0f2216663ab2efbdc6e4fc323471b
Status: Downloaded newer image for …
```
=> chore: add instadefi ssl cert to docker image
